### ISSUE TITLE
this.unsubscribeFormat is not a function error

### ISSUE THREAD

**Issue by sametkuru** [angularfy/ng-autonumeric#36]
Hi,
When I refresh the page (CTRL + R / F5), I get this error in the ngOnDestroy method and my component does not open.

**Comment by ainouss** [comment]
Hello sametkuru can you please provide more details ?

**Comment by aleksander351** [comment]
> Hi, When I refresh the page (CTRL + R / F5), I get this error in the ngOnDestroy method and my component does not open.

Same here when running tests.

`TypeError: this.unsubscribeFormat is not a function
            at AutonumericDirective.call [as ngOnDestroy] (node_modules/@angularfy/autonumeric/__ivy_ngcc__/fesm2015/angularfy-autonumeric.js:204:14)
            at executeOnDestroys (node_modules/@angular/core/fesm2020/core.mjs:6449:32)`
